include:
    - project: "epi2melabs/ci-templates"
      file: "wf-containers.yaml"

variables:
    RUN: "./nextflow run main.nf -w ${OUTPUT}/workspace --out_dir ${OUTPUT} --fastq test_data/reads.fq.gz"

conda-run:
    extends: .conda-run
    script:
        - "${RUN} -profile conda"

docker-run:
    extends: .docker-run
    script:
        - "${RUN} -profile standard --wfversion latest"
