name: epi2melabs-wf-metagenomics
channels:
    - epi2melabs
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - python==3.8.*
    - bokeh==2.4.*
    - aplanat >=0.3.5
    - pysam >=0.17.0
    - pandas
    - fastcat
    - minimap2
    - samtools
    - kraken2
    - krakentools
    - seqkit 
    - taxonkit
    - bracken
    - epi2melabs
    - natsort
    - kraken2-server>=0.0.5
