name: epi2melabs-nf-template-workflow
channels:
    - epi2melabs
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - python==3.8.*
    - aplanat >=0.3.5
    - pysam
    - pandas
    - holoviews
    - fastcat
    - minimap2
    - samtools
    - kraken2
    - krakentools
    - seqkit 
    - taxonkit
    - mapula
    - bracken
